# JOYENT LDAP KIT 					  Configuration Makefile
################################################################################

KIT_ROOT=	`pwd`
HOST=		`hostname`
DATE=		`date +%m.%d.%y-%H:%M:%S`

DIT_SUFFIX=	dc=example,dc=com
NISDOMAIN=	example.com
NISDC=		example

# Your PRIMARY LDAP server is "pref", your SECONDARY is "server"
# The name MUST match the CN in your TLS certs and be in /etc/hosts!
PREFSERVERS=	ldap0.example.com:636
SERVERS=		ldap1.example.com:636

SERVER1_HOSTENTRY=	"10.10.10.11      ldap0.example.com ldap0"
SERVER2_HOSTENTRY=	"10.10.10.12      ldap1.example.com ldap1"

# Generate 256-bit key equivalent passwords with `openssl rand -hex 16`
ROOTDN_PASS=		secret
MIRROR_PASS=		secret
PROXY_PASS=			secret

PASS_HASH=			{CRYPT}
CRYPT_FORMAT=		-c '$$5$$%.8s'

# The hashed version of the above, can not include /'s;.come: slappasswd -s $(ROOTDN_PASS)
ROOTDN_PASS_HASH=	`slappasswd -h '$(PASS_HASH)' $(CRYPT_FORMAT) -s $(ROOTDN_PASS)`
MIRROR_PASS_HASH=	`slappasswd -h '$(PASS_HASH)' $(CRYPT_FORMAT) -s $(MIRROR_PASS)`
PROXY_PASS_HASH=	`slappasswd -h '$(PASS_HASH)' $(CRYPT_FORMAT) -s $(ROOTDN_PASS)`

# These certs and keys should be placed in the pki/ directory
TLS_CA_CERT=	ca.crt
TLS_SRV_CERT=	server.crt
TLS_SRV_KEY=	server.key


MIRROR_PEER_IP=	10.10.10.10
